#!/usr/bin/env bash

set -o nounset
set -o errexit
set -o errtrace

ktest_workdir="/home/ktest/ktest"

usage()
{
    echo "podman-ktest: Run generic virtual machine tests"
    echo "Usage: podman-ktest cmd [options]"
}

if [[ $# = 0 ]]; then
    usage
    exit 1
fi

function cmd_build() {
    podman build \
	   -t ktest-runner \
	   -f ci-lustre/Containerfile.ktest-runner \
	   .
}

function cmd_run() {
    podman run \
	   -it \
	   --workdir "$ktest_workdir" \
	   --tty --interactive=false \
	   --pids-limit 100000 \
	   --device /dev/kvm \
	   -v /home/admin/Programming/linux:/home/ktest/git/linux:O \
	   -v /home/admin/Programming/lustre-release/:/home/ktest/git/lustre-release/:O \
	   -v /var/lib/ktest/:/var/lib/ktest/:O \
	   -v /tmp/:/tmp/ \
	   --rm ktest-runner:latest "$@"
}

function cmd_run_immutable() {
    podman run \
	   -it \
	   --workdir "$ktest_workdir" \
	   --pids-limit 100000 \
	   --tty --interactive=false \
	   --device /dev/kvm \
	   -v /home/admin/Programming/linux:/home/ktest/git/linux:O \
	   -v /home/admin/Programming/lustre-release/:/home/ktest/git/lustre-release/:O \
	   -v /var/lib/ktest/:/var/lib/ktest/:O \
	   -v /tmp/:/tmp/:O \
	   --rm ktest-runner:latest "$@"
}

function cmd_build_u24() {
    podman build \
	   -t lustre-u24 \
	   -f ci-lustre/Containerfile.u24 \
	   .
    podman run \
	   -it \
	   --workdir /home/root/git/lustre-release/ \
	   --pids-limit 100000 \
	   --tty --interactive=false \
	   -v /home/admin/Programming/lustre-release/:/home/root/git/lustre-release/:O \
	   --rm lustre-u24:latest \
	   bash -c '
pwd
echo "Running tests..."
./autogen.sh
./configure --disable-server
make -j$(nproc)
       '
}

function cmd_build_al2023() {
    podman build \
	   -t lustre-al2023 \
	   -f ci-lustre/Containerfile.al2023 \
	   .
    podman run \
	   -it \
	   --workdir /home/root/git/lustre-release/ \
	   --pids-limit 100000 \
	   --tty --interactive=false \
	   -v /home/admin/Programming/lustre-release/:/home/root/git/lustre-release/:O \
	   --rm lustre-al2023:latest \
	   bash -c '
pwd
echo "Running tests..."
./autogen.sh
./configure
make -j$(nproc)
       '
}

function cmd_build_al2() {
    podman build \
	   -t lustre-al2 \
	   -f ci-lustre/Containerfile.al2 \
	   .
    podman run \
	   -it \
	   --workdir /home/root/git/lustre-release/ \
	   --pids-limit 100000 \
	   --tty --interactive=false \
	   -v /home/admin/Programming/lustre-release/:/home/root/git/lustre-release/:O \
	   --rm lustre-al2:latest \
	   bash -c '
pwd
echo "Running tests..."
./autogen.sh
./configure
make -j$(nproc)
       '
}

# parse command and shift for rest of arg parsing
CMD="$1"
shift

# check if command is valid
if [[ $(type -t "cmd_$CMD") == function ]]; then
    CMD="cmd_$CMD"
else
    usage
    exit 1
fi

while getopts "w:h" arg; do
    case $arg in
	w)
	    ktest_workdir="$OPTARG"
	    ;;
	h)
	    usage
	    exit 0
	    ;;
    esac
done
shift $((OPTIND - 1))

$CMD "$@"
