#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-2.0

#
# Modified for Lustre: Timothy Day <timday@amazon.com>
#

set -o nounset
set -o errexit
set -o errtrace

ktest_dir=$(dirname "$(readlink -f "$0")")

. "$ktest_dir/lib/libktest.sh"

checkdep clang
checkdep bison
checkdep bear
checkdep flex
checkdep make
checkdep gcc
checkdep bc

# Lustre parameters
export CC="${CC:-clang-20}"
export FSTYPE="wbcfs"

# Ktest parameters
ktest_kernel_source="$(realpath ~/git/linux/ 2>/dev/null || true)"
ktest_lustre_source="$ktest_kernel_source/../lustre-release/"
ktest_boot_test="$ktest_dir/tests/fs/lustre/boot.ktest"
ktest_ccplugin="$ktest_dir/../xunused/build/xunused"
ktest_compiler="${CC:-clang-20}"
ktest_skip_kernel_config=false
ktest_lustre_allow_warnings=0
ktest_lustre_build_enable=1
ktest_kernel_build_enable=1
ktest_out="/tmp/ktest-out/"
ktest_root_image="$ktest_out/root.amd64.new"
ktest_lustre_clean_git=0
ktest_lustre_purge=0
ktest_njobs=$(nproc)
ktest_precise=false
ktest_loop=false
DEPMOD=depmod
MAKEARGS=()
COVERAGE=""

if ! which depmod > /dev/null; then
    DEPMOD=/sbin/depmod
fi

function usage()
{
    echo "qlkbuild: Quick Lustre Kernel Build"
    echo "Usage: qlkbuild cmd [options]"
    ktest_usage_cmds
    echo "  build <test>        Build kernel for a test configuration"
    echo "  ccplugin <test>     Build and run CC plugin"
    echo "  oldconfig           Run make oldconfig"
    echo "  config              Run make nconfig"
    echo
    ktest_usage_post
}

if [[ $# = 0 ]]; then
    usage
    exit 1
fi

# Parse command
CMD="$1"
shift

while getopts "h${ktest_args}" arg; do
    case $arg in
	h)
	    usage
	    exit 0
	    ;;
    esac
    parse_ktest_arg $arg
done
shift $(( OPTIND - 1 ))

parse_args_post

# default parameters
[[ -z $ktest_kernel_source ]]	&& ktest_kernel_source="."

if [[ ! -d $ktest_kernel_source ]]; then
    echo "kernel source directory $ktest_kernel_source does not exist"
    exit 1
fi

ktest_kernel_source=$(readlink -e "$ktest_kernel_source")

ktest_kernel_build="$ktest_out/kernel_build.$ktest_arch"
ktest_lustre_build="$ktest_out/lustre_build.$ktest_arch"
mkdir -p "$ktest_kernel_build"
mkdir -p "$ktest_lustre_build"

if [[ -n $CROSS_COMPILE ]]; then
    checkdep "$ARCH_TRIPLE-gcc" "gcc-$ARCH_TRIPLE"
fi

function check_file() {
    local file="$1"

    if [[ ! -f "$file" ]]; then
	echo "$file not found!"
	exit 1
    fi

    return 0
}

function validate_lustre_build() {
    check_file "$ktest_lustre_build/lnet/lnet/lnet.ko"
    check_file "$ktest_lustre_build/lustre/llite/lustre.ko"
    check_file "$ktest_lustre_build/lustre/osd-wbcfs/osd_wbcfs.ko"
}

function sync_root_image() {
    "$ktest_dir/root_image" sync
}

function create_root_image() {
    local old="$PWD"

    cd "$ktest_lustre_build"
    run_quiet_with_status "UPDATE ROOT IMAGE" "DONE" sync_root_image
    cd "$old"
}

function cmd_run()
{
    if [[ $# = 0 ]]; then
	ktest_test="$ktest_boot_test"
    else
	ktest_test=$(realpath "$1")
	shift
    fi

    ktest_testargs="$@"
    parse_test_deps "$ktest_test"

    create_root_image

    start_vm
}

function build_lustre()
{
    local old="$PWD"
    local LINUX_OBJ="/tmp/ktest-out/kernel_build.x86_64/"
    local SUBARCH="x86"

    cd "$ktest_lustre_build"

    rsync --archive -r "$ktest_lustre_source" "$ktest_lustre_build"

    # No strict errors
    if [[ "${ktest_lustre_allow_warnings}" == "1" ]]; then
	export CFLAGS="-Wno-error=attribute-warning -Wno-error=unused-but-set-variable -Wno-error=single-bit-bitfield-constant-conversion -Wno-error=format-security -Wno-error=cast-function-type-strict"
    else
	export CFLAGS="-Werror"
    fi

    # Find headers
    export CFLAGS="$CFLAGS -I$LINUX_OBJ/include"
    export CFLAGS="$CFLAGS -I$LINUX_OBJ/include"
    export CFLAGS="$CFLAGS -I$LINUX_OBJ/arch/$SUBARCH/include/generated"
    export CFLAGS="$CFLAGS -I$LINUX_OBJ/arch/$SUBARCH/include/generated/uapi"
    export CFLAGS="$CFLAGS -I$LINUX_OBJ/include/generated"
    export CFLAGS="$CFLAGS -I$LINUX_OBJ/include/generated/uapi"
    export KCFLAGS="-I$LINUX_OBJ/include"
    export KCFLAGS="$KCFLAGS -I$LINUX_OBJ/arch/$SUBARCH/include/generated"
    export KCFLAGS="$KCFLAGS -I$LINUX_OBJ/arch/$SUBARCH/include/generated/uapi"
    export KCFLAGS="$KCFLAGS -I$LINUX_OBJ/include/generated"
    export KCFLAGS="$KCFLAGS -I$LINUX_OBJ/include/generated/uapi"

    # Disable persistent OSDs
    export with_ldiskfs="no"
    export with_zfs="no"

    # Disable optional features
    export with_o2ib="no"
    export enable_gss="no"

    # Always build the server
    export enable_server="yes"

    # ktest uses statically linked tools
    export enable_shared="no"

    # Assume that Linux is in the same directory as Lustre
    export with_linux="$ktest_kernel_source"

    # Build the kernel via ktest into tmp
    export ARCH="$(uname -m)"
    export with_linux_obj="/tmp/ktest-out/kernel_build.$ARCH/"

    # Misc
    export LLVM="-20"

    ./autogen.sh
    ./configure
    bear -- make -j$ktest_njobs

    # Newer kernels have these lines that the plugin hates
    sed -i '/-Wp,-MMD,.*\.d/d' "$ktest_lustre_build/compile_commands.json"

    validate_lustre_build

    cd "$old"
}

function cmd_build()
{
    if [[ $# = 0 ]]; then
	ktest_test="$ktest_boot_test"
    else
	ktest_test=$(realpath "$1")
	shift
    fi

    ktest_testargs="$@"
    parse_test_deps "$ktest_test"

    if [[ -n $COVERAGE ]]; then
	ktest_kernel_config_require+=(GCOV_KERNEL)
    fi

    run_quiet_with_status "KERNEL BUILD [$(basename "$ktest_test")]" "DONE" build_kernel
    run_quiet_with_status "LUSTRE BUILD [$(basename "$ktest_test")]" "DONE" build_lustre

    # Purge junk from ktest_out to save space
    find "$ktest_out" -name '*.o' -type f -delete
}

function cmd_help()
{
    usage
}

if [[ $(type -t "cmd_$CMD") == function ]]; then
    CMD="cmd_$CMD"
elif [[ $(type -t "ktest_$CMD") == function ]]; then
    CMD="ktest_$CMD"
else
    usage
    exit 1
fi

$CMD "$@"
