#!/bin/bash
# SPDX-License-Identifier: GPL-2.0-only

#
# Display the license status of files in the current directory
# using 'reuse lint' from the REUSE tool
#

exec reuse --root "${1:-$(pwd)}" lint
